INSERT INTO [dbo].[Toys] ([id], [price], [aisle_id], [name], [quantity_in_stock], [description]) VALUES (1, CAST(11 AS Decimal(18, 0)), 5, N'Autobot', N'100', N'Truck Toy')
INSERT INTO [dbo].[Toys] ([id], [price], [aisle_id], [name], [quantity_in_stock], [description]) VALUES (2, CAST(12 AS Decimal(18, 0)), 5, N'StarScream', N'76', N'Truck Toy')
INSERT INTO [dbo].[Toys] ([id], [price], [aisle_id], [name], [quantity_in_stock], [description]) VALUES (3, CAST(11 AS Decimal(18, 0)), 5, N'BumbleBee', N'113', N'Truck Toy')
INSERT INTO [dbo].[Toys] ([id], [price], [aisle_id], [name], [quantity_in_stock], [description]) VALUES (4, CAST(9 AS Decimal(18, 0)), 10, N'BattleBot', N'45', N'Collapsable Truck')
INSERT INTO [dbo].[Toys] ([id], [price], [aisle_id], [name], [quantity_in_stock], [description]) VALUES (5, CAST(10 AS Decimal(18, 0)), 20, N'Flipazoo', N'80', N'Plush Toy')
INSERT INTO [dbo].[Toys] ([id], [price], [aisle_id], [name], [quantity_in_stock], [description]) VALUES (6, CAST(13 AS Decimal(18, 0)), 15, N'TurboMan', N'45', N'Action Figure')
INSERT INTO [dbo].[Toys] ([id], [price], [aisle_id], [name], [quantity_in_stock], [description]) VALUES (7, CAST(15 AS Decimal(18, 0)), 15, N'Batman', N'67', N'Action Figure')
INSERT INTO [dbo].[Toys] ([id], [price], [aisle_id], [name], [quantity_in_stock], [description]) VALUES (8, CAST(6 AS Decimal(18, 0)), 15, N'Peter Porker', N'89', N'Action Figure')
INSERT INTO [dbo].[Toys] ([id], [price], [aisle_id], [name], [quantity_in_stock], [description]) VALUES (9, CAST(15 AS Decimal(18, 0)), 15, N'SuperMan', N'54', N'Action Figure')
INSERT INTO [dbo].[Toys] ([id], [price], [aisle_id], [name], [quantity_in_stock], [description]) VALUES (11, CAST(5 AS Decimal(18, 0)), 15, N'Captain America', N'20', N'Action Figure')
INSERT INTO [dbo].[Toys] ([id], [price], [aisle_id], [name], [quantity_in_stock], [description]) VALUES (12, CAST(1 AS Decimal(18, 0)), 15, N'HotWheels', N'60', N'Small car')
